-- 30名分のダミー社員と掃除エリア、直近1週間の当番割当
SET NAMES utf8mb4;
USE cleaning;

INSERT INTO areas (id, name, description) VALUES
  (1, '会議室A',    '机・椅子の整頓、ホワイトボード消去'),
  (2, '会議室B',    '机・椅子の整頓、プロジェクター電源確認'),
  (3, '休憩スペース', 'シンク・テーブル拭き、ゴミ捨て'),
  (4, 'トイレ',     '清掃業者の補助、消耗品確認'),
  (5, 'エントランス', '床のモップがけ、来客スリッパ整理');

INSERT INTO employees (name, email, department) VALUES
  ('佐藤 一郎',   'sato.ichiro@example.com',    '営業部'),
  ('鈴木 二郎',   'suzuki.jiro@example.com',    '営業部'),
  ('高橋 三郎',   'takahashi.saburo@example.com', '営業部'),
  ('田中 四郎',   'tanaka.shiro@example.com',   '営業部'),
  ('伊藤 五郎',   'ito.goro@example.com',       '開発部'),
  ('渡辺 六郎',   'watanabe.rokuro@example.com', '開発部'),
  ('山本 七海',   'yamamoto.nanami@example.com', '開発部'),
  ('中村 八重',   'nakamura.yae@example.com',   '開発部'),
  ('小林 九美',   'kobayashi.kumi@example.com', '開発部'),
  ('加藤 十子',   'kato.toko@example.com',      '開発部'),
  ('吉田 さくら', 'yoshida.sakura@example.com', '人事部'),
  ('山田 ひかり', 'yamada.hikari@example.com',  '人事部'),
  ('佐々木 健',   'sasaki.ken@example.com',     '人事部'),
  ('山口 翔',     'yamaguchi.sho@example.com',  '経理部'),
  ('松本 美咲',   'matsumoto.misaki@example.com', '経理部'),
  ('井上 拓海',   'inoue.takumi@example.com',   '経理部'),
  ('木村 結衣',   'kimura.yui@example.com',     '総務部'),
  ('林 蓮',       'hayashi.ren@example.com',    '総務部'),
  ('斎藤 陽菜',   'saito.hina@example.com',     '総務部'),
  ('清水 大輔',   'shimizu.daisuke@example.com', '法務部'),
  ('山崎 涼子',   'yamazaki.ryoko@example.com', '法務部'),
  ('森 直樹',     'mori.naoki@example.com',     '広報部'),
  ('阿部 美月',   'abe.mizuki@example.com',     '広報部'),
  ('池田 隼人',   'ikeda.hayato@example.com',   'マーケ部'),
  ('橋本 凛',     'hashimoto.rin@example.com',  'マーケ部'),
  ('石川 蒼',     'ishikawa.aoi@example.com',   'マーケ部'),
  ('山下 詩織',   'yamashita.shiori@example.com', '情シス'),
  ('中島 樹',     'nakajima.itsuki@example.com', '情シス'),
  ('石井 葵',     'ishii.aoi@example.com',      '情シス'),
  ('小川 颯',     'ogawa.hayate@example.com',   '情シス');

-- 直近5営業日 × 5エリア = 25件のラウンドロビン当番割当
INSERT INTO duties (employee_id, area_id, scheduled_date, status) VALUES
  ( 1, 1, CURDATE() + INTERVAL 0 DAY, 'pending'),
  ( 2, 2, CURDATE() + INTERVAL 0 DAY, 'pending'),
  ( 3, 3, CURDATE() + INTERVAL 0 DAY, 'pending'),
  ( 4, 4, CURDATE() + INTERVAL 0 DAY, 'pending'),
  ( 5, 5, CURDATE() + INTERVAL 0 DAY, 'pending'),
  ( 6, 1, CURDATE() + INTERVAL 1 DAY, 'pending'),
  ( 7, 2, CURDATE() + INTERVAL 1 DAY, 'pending'),
  ( 8, 3, CURDATE() + INTERVAL 1 DAY, 'pending'),
  ( 9, 4, CURDATE() + INTERVAL 1 DAY, 'pending'),
  (10, 5, CURDATE() + INTERVAL 1 DAY, 'pending'),
  (11, 1, CURDATE() + INTERVAL 2 DAY, 'pending'),
  (12, 2, CURDATE() + INTERVAL 2 DAY, 'pending'),
  (13, 3, CURDATE() + INTERVAL 2 DAY, 'pending'),
  (14, 4, CURDATE() + INTERVAL 2 DAY, 'pending'),
  (15, 5, CURDATE() + INTERVAL 2 DAY, 'pending'),
  (16, 1, CURDATE() + INTERVAL 3 DAY, 'pending'),
  (17, 2, CURDATE() + INTERVAL 3 DAY, 'pending'),
  (18, 3, CURDATE() + INTERVAL 3 DAY, 'pending'),
  (19, 4, CURDATE() + INTERVAL 3 DAY, 'pending'),
  (20, 5, CURDATE() + INTERVAL 3 DAY, 'pending'),
  (21, 1, CURDATE() + INTERVAL 4 DAY, 'pending'),
  (22, 2, CURDATE() + INTERVAL 4 DAY, 'pending'),
  (23, 3, CURDATE() + INTERVAL 4 DAY, 'pending'),
  (24, 4, CURDATE() + INTERVAL 4 DAY, 'pending'),
  (25, 5, CURDATE() + INTERVAL 4 DAY, 'pending');
